
- hosts: linux_centos_ubuntu_debian
  gather_facts: true
  become: true
when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- name: Add multiple repositories into the same file 
  yum_repository:
    name: rpmforge
    description: RPMforge YUM repo
    file: external_repos
    baseurl: http://apt.sw.be/redhat/el7/en/$basearch/rpmforge
    mirrorlist: http://mirrorlist.repoforge.org/el7/mirrors-rpmforge

# repository for linux and centos
- name: install Percona XtraDB Cluster 5.7
  yum: pkg=Percona XtraDB Cluster 5.7 state=present

when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
# repsitory for ubuntu and debian
- apt_repository:
    repo: deb http://archive.canonical.com/ubuntu hardy partner
    state: present

- name: install Percona XtraDB Cluster 5.7
  apt: pkg=Percona XtraDB Cluster 5.7 state=present
-name: ensure Percona XtraDB Cluster 5.7 is running
 service: name=XtraDB Cluster 5.7 state=started

# Path to Galera library
wsrep_provider=/usr/lib64/libgalera_smm.so

# Data directory
xtradb_datadir: /var/lib/mysql
# Defines the user used
xtradb_mysql_user: mysql
roles:
    - role: ansible-role-XtraDB-Cluster
      xtradb_cluster_name: "prod-customer"
      xtradb_sst_user: sstuser
      xtradb_sst_password: s3cr3t
      xtradb_root_password: narendra
      xtradb_nodes_group: "linux_centos_ubuntu_debian"
      xtradb_bind_interface: eth0
      xtradb_innodb_buffer_pool_instances: 8
      xtradb_innodb_buffer_pool_size: "384M"
      xtradb_innodb_file_format: "Barracuda"
      xtradb_innodb_file_format_check: "1"
      xtradb_innodb_file_per_table: "on"
      xtradb_innodb_flush_log_at_trx_commit: "1"
      xtradb_innodb_log_buffer_size: "16M"
      xtradb_innodb_log_file_size: "50M"
      xtradb_innodb_strict_mode: "on"
      xtradb_join_buffer_size: "128K"
      xtradb_log_warnings: "1"
      xtradb_long_query_time: "10"
      xtradb_max_allowed_packet: "16M"
      xtradb_max_connections: "505"
      xtradb_max_heap_table_size: "16M"
      xtradb_max_user_connections: "500"
      xtradb_query_cache_size: "0"   # disable
      xtradb_read_buffer_size: "128K"
      xtradb_read_rnd_buffer_size: "256k"
      xtradb_skip_name_resolve: "1"
      xtradb_slow_query_log: "1"
      xtradb_sort_buffer_size: "2M"
      xtradb_table_definition_cache: "1400"
      xtradb_table_open_cache: "2000"
      xtradb_table_open_cache_instances: "8"
      xtradb_tmp_table_size: "16M"

# Define the node pool 
xtradb_wsrep_cluster_address: "gcomm://{{ groups[linux_centos_ubuntu_debian] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',') }}"
xtradb_wsrep_cluster_address: "gcomm://{{ groups[linux_centos_ubuntu_debian] | map('extract', hostvars, ['ansible_' ~ xtradb_bind_interface, 'ipv4', 'address']) | join(',') }}"

# Defines the which node should be considered the master in the cluster
# Used to bootstrap cluster
xtradb_master_node: "{{ hostvars[ groups[linux_centos_ubuntu_debian][0] ].ansible_default_ipv4.address }}"
